[contest]
name = "test"
description = "Test"
token_mode = "infinite"

[[contest.users]]
username = "u1"
password = "p1"

[contest-config]
languages = ["C11 / gcc", "C++17 / g++", "Java / JDK", "Python 3 / CPython"]

[contest-config.mapping]
"C11 / gcc" = [".c"]
"C++17 / g++" = [".cpp", ".cc", ".cxx", ".c++", ".C"]
"Java / JDK" = [".java"]
"Python 3 / CPython" = [".py"]

[task_template]
infile = ""
outfile = ""
task_type = "Batch"
score_mode = "max_subtask" # 2017~
token_mode = "infinite"
score_type = "GroupMin"
score_type_parameters = ""
time_limit = 15
memory_limit = 1024

[[tasks]]
name = "taxi"
title = "taxi"
time_limit = "1.0"
  [tasks.inclusive_tests]
  2 = ["0", "1"]

[[tasks]]
name = "paint"
title = "paint"
time_limit = 1.0
  [tasks.inclusive_tests]
  2 = ["0"]
  3 = ["0", "1", "2"]

[[tasks]]
name = "nums"
title = "nums"
time_limit = "1.0"
  [tasks.inclusive_tests]
  2 = ["0", "1"]
  3 = ["0", "1", "2"]

[[tasks]]
name = "cover"
title = "cover"
task_type = "OutputOnly"
output_only = true
submission_format = [
  "output_1_1.txt",
  "output_2_1.txt",
  "output_3_1.txt",
  "output_4_1.txt",
  "output_5_1.txt",
  "output_6_1.txt",
  "output_7_1.txt",
  "output_8_1.txt",
  "output_9_1.txt",
  "output_10_1.txt"
]

[[tasks]]
name = "huaguo"
title = "huaguo"
time_limit = "3.0"
  [tasks.inclusive_tests]
  3 = ["1", "2"]
  5 = ["0", "1", "2", "3", "4"]

[[tasks]]
name = "indset"
title = "indset"
time_limit = 1.0
  [tasks.inclusive_tests]
  3 = ["0", "1", "2"]

[[tasks]]
name = "television"
title = "television"
time_limit = 1.0
  [tasks.inclusive_tests]
  2 = ["1"]
  3 = ["1", "2"]
  4 = ["0", "1", "2", "3"]

[[tasks]]
name = "fingerprint"
title = "fingerprint"
time_limit = 1.0
  [tasks.inclusive_tests]
  1 = ["0"]
  2 = ["0"]
  3 = ["0", "1", "2"]

[[tasks]]
name = "pirate"
title = "pirate"
time_limit = 3.0
  [tasks.inclusive_tests]
  1 = ["0"]
  2 = ["0"]
  3 = ["0", "1"]
  4 = ["0", "1", "2", "3"]

[[tasks]]
name = "collinear"
title = "collinear"
time_limit = 1.0
  [tasks.inclusive_tests]
  2 = ["0"]
  3 = ["0", "1", "2"]

[[tasks]]
name = "permutation"
title = "permutation"
time_limit = 1.0
  [tasks.inclusive_tests]
  2 = ["0", "1"]

[[tasks]]
name = "sudoku"
title = "sudoku"
task_type = "OutputOnly"
output_only = true
submission_format = [
  "output_1_1.txt",
  "output_2_1.txt",
  "output_3_1.txt",
  "output_4_1.txt",
  "output_5_1.txt",
  "output_6_1.txt",
  "output_7_1.txt",
  "output_8_1.txt",
  "output_9_1.txt",
  "output_10_1.txt"
]
